DATA SEGMENT
ARR DW 1234H,1342H,2345H,3456H,4657H
LEN DW ($-ARR)/2
KEY EQU 3456H
ASCI1 EQU (KEY/1000H)+'0'
ASCI2 EQU (KEY/100H)MOD 10H+'0'
ASCI3 EQU (KEY/10H)MOD 10H+'0'
ASCI4 EQU (KEY MOD 10H)+'0'
MSG1 DB 10,13, "ELEMENT ",ASCI1,ASCI2,ASCI3,ASCI4, " NOT FOUND"
MSG2 DB 10,13, "ELEMENT ",ASCI1,ASCI2,ASCI3,ASCI4, " FOUND AT POSITION "
RESULT DB ?, '$'
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:
MOV AX,DATA
MOV DS,AX
MOV BX,01H
MOV DX,LEN
MOV CX,KEY
AGAIN:
CMP BX,DX
JA FAIL
MOV AX,BX
ADD AX,DX
SHR AX,01
MOV SI,AX
DEC SI
ADD SI,SI
CMP CX,ARR[SI]
JAE BIG
DEC AX
MOV DX,AX
JMP AGAIN
BIG: JE SUCCESS
INC AX
MOV BX,AX
JMP AGAIN
SUCCESS:
ADD AL,'0'
MOV RESULT,AL
LEA DX,MSG2
JMP DISP
FAIL:LEA DX,MSG1
DISP:MOV AH,09H
INT 21H
MOV AH,4CH
INT 21H
CODE ENDS
END START