DATA SEGMENT
ARRAY1 DB 'GOOD'
ARRAY2 DB 'GOD'
CNT DB 04H
STR1 DB 'STRINGS ARE EQUAL $'
STR2 DB 'STRINGS ARE UNEQUAL $'
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA,ES:DATA
START:
MOV AX,DATA
MOV DS,AX
MOV ES,AX
MOV CL,CNT
LEA SI,ARRAY1
LEA DI,ARRAY2
REP CMPSB
JNZ L1
LEA DX,STR1
JMP L2
L1:LEA DX,STR2
L2:MOV AH,09H
INT 21H
MOV AH,4CH
INT 21H
CODE ENDS
END START