DATA SEGMENT
STRING DB 'MALAYALAM$'
STRING1 DB 'STRING IS PALINDROME$'
STRING2 DB 'STRING IS NOT PALINDROME$'
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:
MOV AX,DATA
MOV DS,AX
MOV SI,OFFSET STRING
LOOP1:
MOV AL,[SI]
CMP AL,'$'
JE LABEL1
INC SI
JMP LOOP1
LABEL1: MOV DI,OFFSET STRING
DEC SI
LOOP2:
CMP SI,DI
JL OUTPUT1
MOV AL,[SI]
MOV BL,[DI]
CMP AL,BL
JNE OUTPUT2
DEC SI
INC DI
JMP LOOP2
OUTPUT1: LEA DX,STRING1
MOV AH,09H
INT 21H
MOV AH,4CH
INT 21H
OUTPUT2: LEA DX,STRING2
MOV AH,09H
INT 21H
MOV AH,4CH
INT 21H
CODE ENDS
END START