DATA SEGMENT
MESSAGE DB 'ENTER PASSWORD PLEASE:$'
PASSWD DB 'FAHEEM'
COUNT DW 6
CORRECT DB 10,13, 'PASSWORD VERFIED AND CORRECT$'
NOTCORRECT DB 10,13, 'INVALID PASSWORD$'
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:
MOV AX,DATA
MOV DS,AX
MOV CX,COUNT
MOV BX,OFFSET PASSWD
;Display message
MOV DX,OFFSET MESSAGE
MOV AH,09H
INT 21H
AGAIN:
MOV AH,08H
INT 21H
CMP AL,[BX]
JNE ERROR
INC BX
LOOP AGAIN
MOV DX,OFFSET CORRECT
MOV AH,09H
INT 21H
JMP OVER
ERROR:
MOV DX,OFFSET NOTCORRECT
MOV AH,09H
INT 21H
OVER:
MOV AH,4CH
INT 21H
CODE ENDS
END START